# Generated by Django 5.1 on 2024-08-17 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livro', '0002_alter_livros_options_livros_autor_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='livros',
            name='autor',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='livros',
            name='nome',
            field=models.CharField(blank=True, max_length=70, null=True),
        ),
    ]
