# Generated by Django 5.1 on 2024-08-20 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livro', '0013_rename_nome_emprestado_emprestimos_usuario_emprestado_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='livros',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='capa_livro'),
        ),
    ]
