# Generated by Django 5.1 on 2024-08-20 19:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('livro', '0014_livros_img'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='livros',
            name='emprestado',
        ),
    ]
