# Generated by Django 5.1 on 2024-08-20 19:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('livro', '0015_remove_livros_emprestado'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='emprestimos',
            options={},
        ),
    ]
