# Generated by Django 5.1 on 2024-08-20 19:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('livro', '0019_remove_emprestimos_data_emprestimo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emprestimos',
            name='usuario_emprestado',
        ),
    ]
