# Generated by Django 5.1 on 2024-08-22 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livro', '0020_remove_emprestimos_usuario_emprestado'),
    ]

    operations = [
        migrations.AddField(
            model_name='livros',
            name='pdf',
            field=models.FileField(blank=True, null=True, upload_to='pdf'),
        ),
    ]
